<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="dashboard_granos-20240502181421" tests="1" file=".py" time="29.165" timestamp="2024-05-02T18:14:50" failures="0" errors="1" skipped="0">
	<testcase classname="dashboard_granos" name="test_dashboard_grain" time="29.165" timestamp="2024-05-02T18:14:50" file="DashboarGranos.py" line="23">
		<error type="TypeError" message="calendar_todate() takes 2 positional arguments but 3 were given"><![CDATA[Traceback (most recent call last):
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\DashboarGranos.py", line 53, in test_dashboard_grain
    calendar_todate(self.driver, select_data_day, popup_calendar1)
TypeError: calendar_todate() takes 2 positional arguments but 3 were given
]]></error>
	</testcase>
</testsuite>
