<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Cuentacontrato.contrato_tenant-failed" tests="1" file="Cuentacontrato.py" time="57.177" timestamp="2024-05-24T11:13:55" failures="1" errors="0" skipped="0">
	<testcase classname="Cuentacontrato.contrato_tenant" name="test_contrato_tenant" time="57.177" timestamp="2024-05-24T11:13:55" file="Cuentacontrato.py" line="22">
		<failure type="AssertionError" message=""><![CDATA[Traceback (most recent call last):
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\Cuentacontrato.py", line 96, in test_contrato_tenant
    validate_text_visible(self.driver, element1, number_expected)
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\Elements.py", line 1145, in validate_text_visible
    assert text_obtained == text_expected
AssertionError
]]></failure>
		<system-out><![CDATA[¡Elemento encontrado y clickeado 6 veces con éxito!
¡Elemento encontrado y clickeado 1 veces con éxito!
El texto encontrado es  Estado De Mis Contratos
El texto es visible para el usuario
]]></system-out>
	</testcase>
</testsuite>
